log/urls.py
from django.conf.urls import url


from . import views


urlpatterns = [
  
     url(r'^$', views.loggin, name='login'),
     
#      url(r'^fiche/(?P<track_pseudo>\w+)$', views.fiche_track, name='fiche_track'),
     url(r'^fiche/(?P<track_pseudo>.*)$', views.fiche_track, name='fiche_track'),
      
      url(r'^(?P<titre_1>.*)/(?P<titre_2>.*)$', views.solo, name='solo'),
    
      url(r'^recommend_songs$', views.recommend_songs, name='recommend_songs'),
      url(r'^save_rating$', views.save_rating, name='save_rating'),
      
      url(r'^auth$', views.auth, name='auth'),
      
      url(r'^logout$', views.loggout, name='logout'),
   
      url(r'^profil$', views.profil, name='profil'),
      
      url(r'^register$', views.register, name='register'),
      url(r'^change_password$', views.change_password, name='change_password'),
   
      
      url(r'^home', views.homepage, name='homepage'),
       url(r'^500', views.custom_500, name='500'),
  
  
]

handler500 = 'app.views.custom_500'

maquette/urls.py
from django.conf.urls import url,include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
       url(r'^', include('log.urls')),
          
       
]

log/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from jsonfield import JSONField
from django.conf import settings
import os
import numpy as np

       

class Profile(models.Model):  
                
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # La liaison OneToOne vers le modèle User
    region = models.CharField(default='', max_length=30)
    area = models.CharField(default='',max_length=30)

    age = models.CharField(default='',max_length=30)
    sex = models.CharField(default='',max_length=30)

    def __str__(self):
        return "Profil de {0}".format(self.user.username)

    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


User.profile = property(lambda u:Profile.objects.get_or_create(user=u)[0])






class Tracks(models.Model):
    track_name=models.CharField(default='',max_length=250)
    track_pseudo=models.CharField(default='',max_length=250)
    track_popularity=models.FloatField(default=0)
    track_genre=models.CharField(default='pop',max_length=250)
    
    
    Artist=models.CharField(default='',max_length=250)
    
    track_link=models.CharField(default='',max_length=250)
    
    Artist_popularity=models.FloatField(default=0)

    Artist_image=models.URLField(blank=True)
    
    Album_name=models.CharField(default='',max_length=250)
    Album_cover=models.URLField(blank=True)
    

    
    duration=models.FloatField(default=0)  ## lenght of the song in ms
    preview=models.URLField(blank=True)  ## preview of 30sec
    nb_rating=models.IntegerField(default=1)
    
    featuring=models.CharField(default='',max_length=250,blank=True)

    
    acousticness=models.FloatField(default=0)
    danceability=models.FloatField(default=0) 
    energy=models.FloatField(default=0)
    instrumentalness=models.FloatField(default=0)
    key=models.IntegerField(default=0)
    liveness=models.FloatField(default=0)
    loudness=models.FloatField(default=0)
    speechiness=models.FloatField(default=0)
    tempo=models.FloatField(default=0)
    time_signature=models.IntegerField(default=0)
    valence=models.FloatField(default=0)
    spotifyID=models.CharField(default='',max_length=250)
    MODE=models.IntegerField(default=0)
    
    
    def __str__(self):
        return self.track_pseudo
    

class Track_Coments(models.Model):
    user=models.ForeignKey(User)
    track=models.ForeignKey(Tracks, on_delete=models.CASCADE)
    rating=models.FloatField(default=0)
    wordcloud=models.CharField(default='',max_length=250)
    time=models.DateTimeField()
#    
def my_default():
    return ['']

#def gen():
#    caracteres = string.ascii_letters + string.digits
#    aleatoire = [random.choice(caracteres) for _ in range(6)]
#    return ''.join(aleatoire)
 
class Traj(models.Model):
    user=models.ForeignKey(User)
    path=JSONField(default=my_default)
    start_time = models.DateTimeField(auto_now_add=True, auto_now=False) 
    key=models.CharField(default='',max_length=50)
    def append(self,txt):
        self.path.append(txt)

    def __str__(self):  # __unicode__ on Python 2
       return self.key

   
def default_songs():
    novelty=np.load(os.path.join(settings.STATIC_ROOT, 'data/novelty.npy')).item()
    return novelty
    
    
    
    
class history(models.Model):
    user=models.ForeignKey(User)
    path=JSONField(default=my_default)
    start_time = models.DateTimeField(auto_now_add=True, auto_now=False) 
    key_traj=JSONField(default=my_default)
    novelty=JSONField(default=default_songs)
    
    def append(self,txt):
        self.path.append(txt)
        
    def append_key(self,txt):
        self.key_traj.append(txt)
        
    def __str__(self):  # __unicode__ on Python 2
       return 'history'





    

log/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Profile, Track_Coments, Traj







class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields = ('area','age','region')      
#    occupation = forms.ChoiceField(choices = occupations, required=True)
#    neighborhood = forms.ChoiceField(choices = neighborhoods, required=True) 
#    region=forms.ChoiceField(choices = regions,required=True)

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=['username','password']
        
#                help_texts = {
#            'username': None,
#        }
#        fields=['username','password','email']
#        labels={'username': 'username'
#                ,}


        
class TracksForm(forms.ModelForm):   
    class Meta:
        model=Track_Coments
        fields = ('rating',) 
        
        
class TrajForm(forms.ModelForm):   
    class Meta:
        model=Traj
        fields = ('path',) 
        

log/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import ( ProfileForm, UserForm)

from django.utils import timezone
        
from .models import Profile, Tracks, Track_Coments  , Traj , history
from django.urls import reverse
from django.contrib.auth import authenticate, login,logout,update_session_auth_hash
from django.contrib.auth.decorators import login_required

from django.contrib.auth.forms import PasswordChangeForm

import datetime
from datetime import time
import timeit

from django.conf import settings
import os
#from wordcloud import WordCloud
import random,string



import numpy as np

from django.db.models import Avg

from itertools import *
import json
from django.http import HttpResponse

from django.views.decorators.csrf import csrf_exempt

#import tensorflow as tf
from neural_network import  history_update,display_songs

os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
#from memory_profiler import profile



def custom_500(request):
    return render(request, '500.html', {}, status=500)

#@profile
def loggin(request):  
    logout(request)
 
    return render(request, 'login.html')    
#@profile    
def auth(request):
        error=False
        username=request.POST.get('username','')
        password=request.POST.get('password','')
        user=authenticate(username=username,password=password)
        
        if user is not None:
                if user.is_active:
                    login(request,user)
                    
                    
                    if Profile.objects.filter(user=request.user).exists():
                        prof = get_object_or_404(Profile, user=request.user)
                        #prof=Profile.objects.filter(user=request.user)
                   
                        if (prof.area=='' or prof.age=='' or prof.region=='' or prof.sex==''):
                            return redirect('profil')
                        else:
                            return redirect(reverse('homepage'))                       
                    else: 
                        #return render(request,'home.html',locals())
                        return redirect('profil')
        else:
            error=True
            return render(request,'login.html',{'error':error})

def loggout(request):
    
    logout(request)
    return redirect(reverse('login'))


#@profile
@login_required 
def homepage(request):
    """'affiche la liste des tracks'""" 
    tracks_list=list(np.load(os.path.join(settings.STATIC_ROOT, 'data/tracks_list.npy'))) 
    random.shuffle(tracks_list)

#    print tracks_list
   
    L=list(np.load(os.path.join(settings.STATIC_ROOT, 'data/L.npy')))
    for r in L:
        random.shuffle(r)
    
    if request.method=='GET':  
        
      
        if Profile.objects.filter(user=request.user).exists():
            prof = get_object_or_404(Profile, user=request.user)
            if (prof.area=='' or prof.age=='' or prof.region=='' or prof.sex==''):
                return redirect('profil')
            else:
              
                
                return render(request,'home.html',locals())
        else:     
            return redirect('profil')
    elif request.method=='POST' :
            if 'next_song' in request.POST:  
                
            ## start creating the trajectory  
                caracteres = string.ascii_letters + string.digits
                aleatoire = [random.choice(caracteres) for _ in range(6)]
                c=request.POST.get('next_song','')             
                t=Traj(path=['start']) 
                t.user=request.user
                t.key=''.join(aleatoire)
                t.save()          
                
                try:      
              
                    t3=Traj.objects.filter(user=request.user).order_by('-start_time')[1]  
                    
                    if (timezone.now()-t3.start_time).seconds >=900:
                    ## was the last conexion of the user more than 30min ago?
                        t2=history(path=['start'])
                        t2.user=request.user
                        t2.save()              
                except:
         
                    ## si pas de history
                    t2=history(path=['start']) 
                    t2.user=request.user
                   
                    t2.save()       
                    
                try:
          
                    t2=history.objects.filter(user=request.user).order_by('-start_time')[0]
                    
                except:
              
                    t2=history(path=['start']) 
                    t2.user=request.user               
                ## delimiteur 
                t2.append('XXX')
                t2.append_key(str(t.key))
          
                t2.save()
               
                return redirect(reverse('fiche_track',kwargs={'track_pseudo': c}))
            
            if 'profil' in request.POST:  
#                track_list = Tracks.objects.order_by('track_name')
                return render(request,'home.html',locals())

@login_required
def profil(request):  

    if request.method=='POST':       
        valid=True
        if 'age' in request.POST:
            if Profile.objects.filter(user=request.user).exists():   
                
                pp=Profile.objects.get(user=request.user)   
                pp.age=request.POST.get('age','')
                pp.region=request.POST.get('region','')
                pp.sex=request.POST.get('sex','')
                pp.area=request.POST.get('area','')
              
                pp.save()
                return render(request,'profil.html',locals())         
            else: 
                profil=ProfileForm
                form=profil(request.POST) 
                age=request.POST.get('age','')
                region=request.POST.get('region','')
                sex=request.POST.get('sex','')
                area=request.POST.get('area','')
                   
                pp=form.save(commit=False)
                pp.age=age
                pp.region=region
                pp.area=area    
                pp.sex=sex      
                pp.user=request.user
                pp.save() 
                return render(request,'profil.html',locals())        
    else:
        if Profile.objects.filter(user=request.user).exists():   
            pp=Profile.objects.get(user=request.user)  
        
        return render(request,'profil.html',locals())
               
def register(request):
    if request.method=='POST':
        #user_is_created=False
        form=UserForm(request.POST)
        #user_is_created=False
        
        if form.is_valid():
            user=form.save(commit=False)
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()
            #user_is_created=True
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('profil')  
        else:
            return render(request,'registration_form.html',{'form':form})
    else:
        form=UserForm(None)
        return render(request,'registration_form.html',{'form':form})
 



@csrf_exempt
def save_rating(request):
    if request.is_ajax():
        if request.method=='POST':
            rating=request.POST.get('rating')
            wordcloud=request.POST.get('wordcloud')
       
            track_pseudo=wcloud=request.POST.get('track_pseudo')
                
            track=get_object_or_404(Tracks, track_pseudo=track_pseudo)
            if not Track_Coments.objects.filter(user=request.user,track=track).exists():               
                t=Track_Coments(rating=rating)
                t.track=track
                t.user=request.user
                t.time=datetime.datetime.now()
                if wcloud!='':      
                    t.wordcloud=wordcloud

 
                    msg={'update_wcloud':True}
                  
                else:
                    msg={'update_wcloud':False}
                t.save()
                
                if Track_Coments.objects.filter(track=track).count()>=10:                        
                    track.track_popularity=Track_Coments.objects.filter(track=track).aggregate(Avg('rating'))['rating__avg']
                    track.save() 
                          
            
            return HttpResponse(json.dumps(msg),content_type="application/json")
    else:
        msg={'error':'No'}
        return HttpResponse(json.dumps(msg),content_type="application/json")
            
#@profile
def recommend_songs(request):
    
    novelty_parameters=5
    songs_by_type_features=np.load(os.path.join(settings.STATIC_ROOT, 'data/songs_by_type_features.npy')).item()
#    print songs_by_type_features['Country'].keys()
    if request.is_ajax():     
        if request.method=='GET':
            songs_db=np.load(os.path.join(settings.STATIC_ROOT, 'data/songs_db.npy')).item()


            t=Traj.objects.filter(user=request.user).order_by('-start_time')[0]  
           
            length=len(t.path)
#            print t.path
#            print 'pathh'
#            print type(str(t.path[length-2]))
            if type(t.path[length-1])==unicode:               
                track_pseudo=t.path[length-1]
          
            elif type(t.path[length-1])==list:
                if len(t.path[length-1])<=2:
                    ### de la forme S(i-3) A(i-2) R(i-1)  donc le state est 
                    track_pseudo=t.path[length-3]
                else:
                    #### S A 
                    
                    track_pseudo=t.path[length-2]
                        
#            track=get_object_or_404(Tracks, track_pseudo=track_pseudo)
            track=songs_db[track_pseudo]
           
            

log/templates/base.html
<!DOCTYPE HTML>
<html >

  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    {% load static %}

    <!-- Bootstrap -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">



     <link rel="stylesheet" href="{% static 'css/base.css' %}" media="screen">

    
</head>

<body >



{% block nav_bar %}

{% endblock  %}

	

{% block content %}

{% endblock  %}

{% block track_list %}

{% endblock  %}



<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>


    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>

<script src="//code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="     
        crossorigin="anonymous"></script>    


<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>


<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

 
<script type='text/javascript' src="{% static 'js/profil.js' %}"></script>   



<script type='text/javascript' src="{% static 'js/home.js' %}"></script>  


  
              
</body>

</html>

log/templates/change_password.html
{% extends "base.html" %}

{% block nav_bar %}
<nav class="navbar navbar-custom" id='grad1'>
  <div class="container-fluid">
     <ul class="nav navbar-nav navbar-right">
      <li class="active">     
       <form action="/home" method="post">
            {% csrf_token %}     
            <input type="hidden"  name='profil' value="0">
            <button class="btn btn-custom btn-md">
              <span class="glyphicon  glyphicon glyphicon-home" aria-hidden="true"></span>               
                    Home
            </button>  
      
    	</form>         
      </li>
     

      </ul> 
  </div>
</nav>
{% endblock  %}



{% block content %}
<br/>
<div class='container'> 	

<form method='post' action=''>
	{% csrf_token %}
	{{ form.as_p}}
	<button type='submit'> Submit </button>
</form>
</div>
</div>



{% endblock %}

log/templates/fiche_track2.html
{% extends "fiche_track_base.html" %}


{% block nav_bar %}


<nav class="navbar navbar-custom" id='grad1'>
  <div class="container-fluid">

  
 
    <ul class="nav navbar-nav navbar-right">
    <li class="active">
 
 <span  id='sortir' class="label label-danger" style="height:35px">Logout when leaving</span>

  </li>
         <li class="active">
        <button class="btn btn-custom btn-md" id='feedback'>
        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> 
            Feedback 
            </button>
        </li>
      <li class="active">
       
           <form id='home' class='form-horizontal' action=""  method='post'>
            {% csrf_token %}
            
            <input type="hidden"  class='percentage2' name='percentage2' value="">
            <input type="hidden"  class='listening_time2' name='listening_time2' value="">
            <input type="hidden"  class='home' name='home' value="home">
           <!--  <button id='home' class='btn btn-warning'>Back home</button> -->
            <button class="btn btn-warning btn-md">
              <span class="glyphicon glyphicon glyphicon-home" aria-hidden="true"></span> 
              
              home
            </button> 
           </form>  
      </li>
  

     
          <li>
     
          <form id='logout' action="" method="post">
            
                {% csrf_token %}
                <input type='hidden' class='liste3' name='liste3' value="{{l}}">
                <input type="hidden"  class='percentage2' name='percentage2' value="">
                <input type="hidden"  class='listening_time2' name='listening_time2' value="">
                 <button class="btn btn-custom btn-md">
                     <span class="glyphicon glyphicon glyphicon-off" aria-hidden="true"></span> 
                   logout       
                   </button>  
                   
               
            </form>

          </li>
    </ul>



    
  </div>
</nav>


{% endblock  %}









 

{% block in_queue2 %}

 
 <div class="col-sm-12  col-md-12  col-lg-12 " id='queue__'>
    <h1> Play when ready</h1>

        <form id='solo' class='solo' action="" method='post'>
                              {% csrf_token %}  
                                <!--  sending variables to django -->
                                
                              <input type="hidden" id='percentage' class='percentage' name='percentage' value="">
                              
                              
                              <input type="hidden" id='listening_time' class='listening_time' name='listening_time' value="">
                                       
                              <br/> 
                              
                              <!--  <button id='load3' class="btn btn-custom6" > -->
                              <span id='artist' class="label label-custom2" name='artist'>{{track2.Artist}}  </span>
                              
                               
                              <span  id='next_song' class="label label-custom2" name='next_song'>{{titre_2}}</span>
                             
                              <!--  <button id='load3' class="btn btn-custom6" > -->
                               <input  id='load3' type='image' src= {{track2.Artist_image}} class="img-circle" alt="artist image"> 
                             
                              <!--  </button> -->

                              <!-- <span id='titre_2' class="label label-info" name='titre_2'>empty</span> -->
                              <input type='hidden' id='next_song' class='next_song' name='solo' value={{titre_2}}>
                              
                        

                          

         </form>
          
           

</div>


{% endblock %}

log/templates/login.html
  
{% extends "base.html" %}


{% block nav_bar %}


<nav class="navbar navbar-custom" id='grad1'>
  <div class="container-fluid">
 <span  id='beta' class="label label-danger"> Beta version 1.0 </span>
 <span  id='beta' class="label label-info"> Use Chrome of Firefox 52.0.1 </span>
    <ul class="nav navbar-nav navbar-right">
 
     
          <li class="active">        
            
             <!--     <form action="/register" method="get">
               				
                      
                	<button  class="btn btn-custom">Register</button>
           		</form>  -->
                   
               
            

      </li>
      </ul>



    
  </div>
</nav>

<br/>
<br/>



{% endblock  %}













{% block content %}
{% if error %}
 <h1>   Wrong username or password </h1>
{% endif %}









<br/>


<br/>
<br/>
<br/>

<!-- <div class='container'> -->
<!-- <div class="col-sm-8 col-md-8  col-lg-8 "> -->
	
	<div class="panel panel-custom" id='login_panel' style="width:30%">
		<div class="panel-heading" id='grad1'>
		<h1> Account  </h1>
		</div>
	

     
      					<div class="panel-body">
      					
    
	
							
								<br/>
						
								<form action="auth" method="post"> 
				    				{% csrf_token %}
				    			<div class='row'>
				    			<div class="form-group" style="width:40%">

							    <div class='input-group'>
							    <span class="input-group-addon" id="basic-addon1"><t class='glyphicon glyphicon-user'></t></span>
							    <input type="text" name='username' value='' class="form-control" placeholder="Username" id="username" aria-describedby="basic-addon1" >
							    </div>
							</div>
								<br/>
							</div>
							  <div class='row'>
							  	<div class="form-group" style="width:40%">
							  		<div class='input-group'>		    	
							    	<span class="input-group-addon" id="basic-addon1"><t class='glyphicon glyphicon-lock'></t></span>
							    	<input type="password" name='password' class="form-control"  value='' id="Password1" placeholder="Password">
							    	</div>
							  	</div>
							  </div>
								
								<br/>
								<div class='row'>
					    		
					    		<button class="btn btn-custom" style="width:40%">Log in</button>
					    		
					    		
					    		</div>
		    					
								</form>

						<br/>


						
						</div>
							<div class="panel-footer">
										 <div class='row'>
										 First time coming?
										 <br/>
										 

										 <form action="/register" method="get">
				               				<!-- {% csrf_token %} -->
				                      
				                		<button  class="btn btn-custom" style="width:40%">Register</button>
				           				</form> 
				           				</div>
			           				</div>
						
						</div>
			
			
	<!-- </div> -->
	<!-- </div> -->



{% endblock %}
	

log/templates/profil.html
{% extends "base.html" %}


{% block nav_bar %}
<nav class="navbar navbar-custom" id='grad1'>
  <div class="container-fluid">
     <ul class="nav navbar-nav navbar-right">
      <li class="active">     
       <form action="/home" method="get">
             
            <input type="hidden"  name='profil' value="0">
            <button class="btn btn-custom btn-md" id="homee">
              <span class="glyphicon  glyphicon glyphicon-home" aria-hidden="true"></span>               
                    Home
            </button>  
      
    	</form>         
      </li>
      <li>
         <form action="/change_password" method="get">
                               
                <button class="btn btn-custom btn-md" id='homee2'>
                reset    
                password</button>
            </form>
            </li>
  
      </ul> 
  </div>
</nav>
{% endblock  %}

















{% block content %}



						<h2 class='uncomplete_form'>   </h2>
						

<table class="table    table-inverse table-responsive">
  <thead>
  <tr> <th colspan="2" class='title'><h3><strong>your settings</strong></h3></th>  
  </tr>
    <tr>  
     
    </tr>
  </thead>
  <tbody>
    
     <tr>
      <th scope="row">sex</th>
      <td class='sexx'><div class='sex' id='sex' >{{pp.sex}}</div> </td>
     
    </tr>
    <tr>
      <th scope="row">age </th>
      <td class='age'><div class='age' id='age'>{{pp.age}}</div></td>
      
      
    </tr>
    <tr >
      <th scope="row">region</th>
      <td class='region'><div class='region' id='region'>{{pp.region}}</div></td>
      
      <td></td>
    </tr>
    <tr>
      <th scope="row">area</th>
      <td class='area'><div class='area' id='area'>{{pp.area}}</div></td>
     
    </tr>
  </tbody>
</table>
<button type='submit' id='change_settings' class="btn btn-danger"> Click here to change</button>
<button type='submit' id='cancel' class="btn btn-custom2"> Cancel</button>
						

						<div class="panel panel-custom" id='cc' style="width:35%">
						

						<div class="panel-heading" id='grad1'> <h1> Profil  </h1>  </div>
						<div class="panel-body">
						 <div id="conteneur">
							<form id='form_rate' class='form-horizontal' action='' method='post'>
							{% csrf_token %}
						<div class='row'>	
						<h5>sex:</h5>
						  <select id="id_sex" name="sex" class="form-group" style="width:40%">
							  <option value="M">M</option>
							  <option value="F">F</option>
						</select>	
						</div>

						<div class='row'>  
						<h5>your age range:</h5>
						<select id="id_age" name="age" class="form-group" style="width:40%">

							  
							  <option value="under 20">under 20</option>
							  <option value="20-25">20-25</option>
							  <option value="26-30" >26-30</option>
							  <option value="31-40" >31-40</option>
							 

						</select>
						</div>

						<div class='row'>
						<h5>region where you live:</h5>
						<select id="id_region" name="region" class="form-group" style="width:40%">
							  <option value="Africa">Africa</option>
							  <option value="Asia">Asia</option>
							  <option value="Europe">Europe</option>
							  <option value="Middle-East">Middle-East</option>
							  <option value="Oceania">Oceania</option>
							  <option value="North-America">North-America</option>
							  <option value="South-America">South-America</option>
						</select>
						</div>
						
						
							
							<div class='row'>
							<h5>professional area:</h5>
							<select id="id_area" name="area" class="form-group" style="width:40%">
							  
							  <option value="Agriculture And Env. Sciences">Agriculture And Env. Sciences</option>
							  <option value="Arts">Arts</option>
							  <option value="Education">Education</option>
							  <option value="Engineering">Engineering</option>
							  <option value="Health">Health</option>
							  <option value="Law">Law</option>
							  <option value="Literature">Literature</option>
							  <option value="Management">Management</option>
							  <option value="Music">Music</option>
							  <option value="Science">Science</option>
							  <option value="Other">Other</option>
							  
							</select>
							</div>
							
							  <br/>
							  <br/>
							 <div class='row'>
							<button type='submit' class="btn btn-custom" id="changes" style="width:40%"> Submit</button>
							 </div>
						</form>
						</div>
						</div>
						</div>
					
						




		



{% endblock %}